patchlevel_event_sourcing_dashboard_default_index:
  path: /
  controller: Patchlevel\EventSourcingDashboardBundle\Controller\DefaultController::indexAction

patchlevel_event_sourcing_dashboard_default_dashboard:
  path: /dashboard
  controller: Patchlevel\EventSourcingDashboardBundle\Controller\DefaultController::dashboardAction

patchlevel_event_sourcing_dashboard_store_show:
  path: /store
  controller: Patchlevel\EventSourcingDashboardBundle\Controller\StoreController::showAction

patchlevel_event_sourcing_dashboard_subscription_show:
  path: /subscription
  controller: Patchlevel\EventSourcingDashboardBundle\Controller\SubscriptionController::showAction

patchlevel_eventsourcingdashboard_subscription_boot:
  path: /subscription/{id}/boot
  controller: Patchlevel\EventSourcingDashboardBundle\Controller\SubscriptionController::bootAction

patchlevel_eventsourcingdashboard_subscription_run:
  path: /subscription/{id}/run
  controller: Patchlevel\EventSourcingDashboardBundle\Controller\SubscriptionController::runAction

patchlevel_eventsourcingdashboard_subscription_rebuild:
  path: /subscription/{id}/rebuild
  controller: Patchlevel\EventSourcingDashboardBundle\Controller\SubscriptionController::rebuildAction

patchlevel_eventsourcingdashboard_subscription_pause:
  path: /subscription/{id}/pause
  controller: Patchlevel\EventSourcingDashboardBundle\Controller\SubscriptionController::pauseAction

patchlevel_eventsourcingdashboard_subscription_setup:
  path: /subscription/{id}/setup
  controller: Patchlevel\EventSourcingDashboardBundle\Controller\SubscriptionController::setupAction

patchlevel_eventsourcingdashboard_subscription_reactivate:
  path: /subscription/{id}/reactivate
  controller: Patchlevel\EventSourcingDashboardBundle\Controller\SubscriptionController::reactivateAction

patchlevel_eventsourcingdashboard_subscription_remove:
  path: /subscription/{id}/remove
  controller: Patchlevel\EventSourcingDashboardBundle\Controller\SubscriptionController::removeAction

patchlevel_event_sourcing_dashboard_inspection_index:
  path: /inspection
  controller: Patchlevel\EventSourcingDashboardBundle\Controller\InspectionController::indexAction

patchlevel_event_sourcing_dashboard_inspection_stream:
  path: /inspection/{stream}
  controller: Patchlevel\EventSourcingDashboardBundle\Controller\InspectionController::streamAction

patchlevel_event_sourcing_dashboard_inspection_show:
  path: /inspection/{aggregateName}/{aggregateId}
  controller: Patchlevel\EventSourcingDashboardBundle\Controller\InspectionController::showAction

patchlevel_event_sourcing_dashboard_event_index:
  path: /event
  controller: Patchlevel\EventSourcingDashboardBundle\Controller\EventController::indexAction

patchlevel_event_sourcing_dashboard_graph_index:
  path: /graph
  controller: Patchlevel\EventSourcingDashboardBundle\Controller\GraphController::indexAction
